export const PUT_USER = 'PUT_USER';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const POST_TOKEN = 'POST_TOKEN';

export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const LOAD_ARTICLE_FAIL = 'LOAD_ARTICLE_FAIL';
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS';

export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'GET_ERRORS';

export const POST_COMMENT = 'GET_ERRORS';
export const POST_COMMENT_SUCCESS = 'GET_ERRORS';
export const POST_COMMENT_FAIL = 'GET_ERRORS';
