name: Bucket
on:
  workflow_call:
  workflow_dispatch:
jobs:
  bucket:
    environment: production
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Create bucket
        working-directory: terraform/bucket
        env:
          YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_FILE }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_ZONE: ${{ secrets.YC_ZONE }}
          AWS_REGION: ${{ secrets.YC_ZONE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Yandex.Cloud S3 to load remote state and to create buckets
          YC_STORAGE_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          YC_STORAGE_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init -upgrade
          terraform plan -input=false
          terraform apply -auto-approve -input=false