name: Deploy
on:
  workflow_call:
  workflow_dispatch:
jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v2

      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      -
        name: Build
        env:
          REACT_APP_BASE_URL: ${{ secrets.BACKEND_DOMAIN }}
        run:
          yarn install
          yarn build

      -
        name: Upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'septacup-frontend'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.YC_ZONE }}
          AWS_S3_ENDPOINT: 'storage.yandexcloud.net'
          SOURCE_DIR: 'build'
